---
title: "01 Regression"
author: "Johnathan Evanilla"
date: "5/4/2022"
output: html_document
---


## Load Packages 

```{r}
library(readr)
library(dplyr)
library(tidymodels)
library(ggplot2)
```


## Read in Data

```{r}
hab <- readr::read_csv(system.file(file.path("input_data", "common_species.csv"), package="globalhabml"))

hab
```

## Get a Summary of the Data

```{r}
summary(hab)
```


## Subset the hab data table to only include features and labels that we want

```{r}
data <- hab %>% 
  select(Chl, Temp, Sal, `Paralia sulcata`) %>% 
  tidyr::drop_na()

data
```


```{r}
summary(data)
```


## Split all of the data into train and test sets

### First create a data split object

```{r}
data_split <- initial_split(data, prop=9/10)

data_split
```



```{r}
data_test <- testing(data_split)
data_train <- training(data_split)
```


```{r}
data_train
```


```{r}
hab_recipe <- recipe(`Paralia sulcata` ~ ., data=data)

hab_recipe
```


```{r}
hist(data$Chl)
hist(data$Temp)
hist(data$Sal)
```


```{r}
hist(log10(data$Chl+1))
```

```{r}
summary(data)
```


```{r}
hab_recipe <- hab_recipe %>% 
  step_log(Chl) %>% 
  step_normalize(all_numeric_predictors())
```


```{r}
hab_recipe <- prep(hab_recipe)

hab_recipe
```


```{r}
prepped_training <- bake(hab_recipe, data_train)
prepped_testing <- bake(hab_recipe, data_test)
```

```{r}
summary(prepped_training)
```


## Linear Regression

```{r}
show_engines("linear_reg")
```


```{r}
lr <- linear_reg() %>% 
  set_mode("regression") %>% 
  set_engine("lm")

lr
```


```{r}
lr_fit <- lr %>% 
  fit(`Paralia sulcata` ~ ., data=prepped_training)

lr_fit
```

```{r}
predict(lr_fit, prepped_testing)
```


```{r}
lr_pred <- augment(lr_fit, prepped_testing)

lr_pred
```



```{r}
lr_metrics <- metrics(lr_pred, truth = `Paralia sulcata`, estimate=.pred)

lr_metrics
```

```{r}
ggplot2::ggplot(data = lr_pred, ggplot2::aes(x=.pred, y=`Paralia sulcata`)) + 
  ggplot2::geom_point() + 
  ggplot2::geom_abline(slope=1, intercept=0)
```

## K-nearest Neighbors



```{r}
show_engines("nearest_neighbor")
```



```{r}
neighbor <- nearest_neighbor(mode = "regression",
                             engine = "kknn")

neighbor
```

```{r}
n_fit <- neighbor %>% 
  fit(`Paralia sulcata` ~ ., data=prepped_training)

n_fit
```

```{r}
n_pred <- augment(n_fit, prepped_testing)
```

```{r}
n_metrics <- metrics(n_pred, truth = `Paralia sulcata`, estimate=.pred)

n_metrics
```

```{r}
lr_metrics
```

## Random Forest

```{r}
show_engines("rand_forest")
```


```{r}
rf <- rand_forest(mode = "regression",
                  engine="ranger")

rf_fit <- rf %>% 
  fit(`Paralia sulcata` ~ ., data=prepped_training)

rf_fit

```


```{r}
rf_pred <- augment(rf_fit, prepped_testing)

rf_metrics <- metrics(rf_pred, truth = `Paralia sulcata`, estimate=.pred)

rf_metrics
```


```{r}
ggplot2::ggplot(data = rf_pred, ggplot2::aes(x=.pred, y=`Paralia sulcata`)) + 
  ggplot2::geom_point() + 
  ggplot2::geom_abline(slope=1, intercept=0)
```

## How can we inprove this model further?

```{r}
summary(hab)
```


```{r}
data <- hab %>% 
  select(Chl, Temp, Sal, PO4, NO3,  NH4,  Si, `Paralia sulcata`) %>% 
  tidyr::drop_na()

data
```

```{r}
hist(data$PO4)
hist(data$NO3)
hist(data$NH4)
hist(data$Si)
```



```{r}
data_split <- initial_split(data, prop=9/10)

data_test <- testing(data_split)
data_train <- training(data_split)
```

```{r}
hab_recipe <- recipe(`Paralia sulcata` ~ ., data=data)

```


```{r}
hab_recipe <- hab_recipe %>% 
  step_log(Chl, PO4, NO3, NH4) %>% 
  step_normalize(all_numeric_predictors())
```

```{r}
hab_recipe <- prep(hab_recipe)
```

```{r}
prepped_training <- bake(hab_recipe, data_train)
prepped_testing <- bake(hab_recipe, data_test)
```


```{r}
rf <- rand_forest(mode = "regression",
                  engine="ranger")

rf_fit <- rf %>% 
  fit(`Paralia sulcata` ~ ., data=prepped_training)

rf_pred_2 <- augment(rf_fit, prepped_testing)

rf_metrics_2 <- metrics(rf_pred_2, truth = `Paralia sulcata`, estimate=.pred)

rf_metrics_2

```

```{r}
rf_metrics
```

```{r}
ggplot2::ggplot(data = rf_pred_2, ggplot2::aes(x=.pred, y=`Paralia sulcata`)) + 
  ggplot2::geom_point() + 
  ggplot2::geom_abline(slope=1, intercept=0)
```

