---
title: "02 Classification"
author: "Johnathan Evanilla"
date: "5/4/2022"
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(tidymodels)
library(ggplot2)
```

```{r}
devtools::load_all()
```


```{r}
hab <- readr::read_csv(system.file(file.path("input_data", "common_species.csv"), package="globalhabml"))

hab
```

```{r}
data <- hab %>% 
  select(Chl, Temp, Sal, `Paralia sulcata`) %>% 
  tidyr::drop_na()

summary(data)
```

```{r}
hist(data$`Paralia sulcata`)
```


```{r}
data <- data %>% 
  mutate(bloom = recode_classification(`Paralia sulcata`, lut=c(0,250)))

data
```

```{r}
data %>% count(bloom)
```

```{r}
data <- data %>% 
  select(-`Paralia sulcata`) %>% 
  mutate(bloom = as.factor(bloom))
```

```{r}
data 
```



```{r}
data_split <- initial_split(data, prop=9/10)

data_test <- testing(data_split)
data_train <- training(data_split)
```

```{r}
hab_recipe <- recipe(bloom ~ ., data=data_split)
```

```{r}
hab_recipe <- hab_recipe %>% 
  step_log(Chl) %>% 
  step_normalize(all_numeric_predictors())

```


```{r}
hab_recipe <- prep(hab_recipe)

hab_recipe
```

```{r}
prepped_training <- bake(hab_recipe, data_train)
prepped_testing <- bake(hab_recipe, data_test)
```


```{r}
rf <- rand_forest(mode = "classification",
                  engine="ranger")

rf_fit <- rf %>% 
  fit(bloom ~ ., data=prepped_training)

rf_pred <- augment(rf_fit, prepped_testing)

rf_metrics <- metrics(rf_pred, truth = bloom, estimate=.pred_class)

rf_metrics

```


```{r}
rf_pred
```


```{r}
conf_mat(rf_pred, truth=bloom, estimate=.pred_class)
```


```{r}
prepped_testing %>% count(bloom)
```


